version: '3'
services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile.prod
    image: thsato/node:prod
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    tty: true
    networks:
      - node-network
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: thsato/nginx:prod
    container_name: nginx
    restart: always
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    image: mysql:8.0
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
